frappe.pages["meta-live-monitor"].on_page_load=function(wrapper){
    const page=frappe.ui.make_app_page({parent:wrapper,title:"Meta Live Monitor",single_column:true});
    const root=$(`<div class="visa-prod"><button class="btn btn-primary btn-sm" data-refresh>Refresh</button><div class="visa-prod-grid"></div><h4>Last Webhook Events</h4><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Webhook</th><th>Event</th><th>Leadgen ID</th><th>Page</th><th>Form</th><th>Dummy/Test</th><th>Real</th><th>Graph</th><th>Queue</th><th>CRM</th><th>Customer</th><th>Visa</th><th>Communication</th><th>Processing</th></tr></thead><tbody></tbody></table></div><pre class="visa-prod-json"></pre></div>`).appendTo(page.body);
    function card(label,value){return `<div class="visa-card"><b>${frappe.utils.escape_html(label)}</b><span>${frappe.utils.escape_html(String(value??""))}</span></div>`}
    function yes(v){return v?"Yes":"No"}
    function dummy(id){id=String(id||"");return id==="444444444444"||id==="987654321"||(id.match(/^\\d+$/)&&id.length<=12)}
    function load(){frappe.call({method:"visa_crm.api.meta_pipeline_audit.meta_health",callback:r=>{const d=r.message||{};root.find(".visa-prod-grid").html([card("Last webhook",d.last_webhook_received),card("Last real webhook",d.last_real_webhook),card("Last Graph",d.last_successful_graph_download),card("Last CRM Lead",d.last_crm_lead_created),card("Last Customer",d.last_customer_created),card("Last Visa",d.last_visa_created),card("Last queue processed",d.last_queue_processed),card("Queue waiting",d.queue_waiting),card("Queue failed",d.queue_failed),card("Queue ignored",d.queue_ignored),card("Graph failures",d.graph_failed_count),card("Token expiry",d.token_expiry)].join(""));root.find(".visa-prod-json").text(JSON.stringify(d,null,2));}});frappe.call({method:"visa_crm.api.meta_pipeline_audit.webhook_audit",callback:r=>{const rows=r.message||[];root.find("tbody").html(rows.map(x=>`<tr><td>${frappe.utils.escape_html(x.received_at||"")}</td><td>${frappe.utils.escape_html(x.event_field||"")}</td><td>${frappe.utils.escape_html(x.leadgen_id||"")}</td><td>${frappe.utils.escape_html(x.page_id||"")}</td><td>${frappe.utils.escape_html(x.form_id||"")}</td><td>${yes(dummy(x.leadgen_id))}</td><td>${yes(!dummy(x.leadgen_id)&&x.event_field==="leadgen")}</td><td>${yes(!!x.graph_response)}</td><td>${yes(!!x.queue)}</td><td>${yes(!!x.crm_lead_created)}</td><td>${yes(!!x.customer)}</td><td>${yes(!!x.visa_application)}</td><td>${yes(!!x.communication_event)}</td><td>${frappe.utils.escape_html(String(x.processing_time||""))}</td></tr>`).join("")||`<tr><td colspan="14">No Meta webhook events found</td></tr>`);}})}
    root.on("click","[data-refresh]",load);load();
};
