frappe.pages["production-tools"].on_page_load=function(wrapper){
    const page=frappe.ui.make_app_page({parent:wrapper,title:"Production Tools",single_column:true});
    const root=$(`<div class="visa-prod"><div class="visa-prod-grid">${["lead","customer","visa_application","communication_event","payment","follow_up"].map(k=>`<button class="btn btn-default" data-demo="${k}">Generate Demo ${k.replace("_"," ")}</button>`).join("")}</div><div class="visa-panel"><input class="form-control" data-queue placeholder="Queue name"><button class="btn btn-primary btn-sm" data-retry>Retry Queue</button></div><div class="visa-panel"><input class="form-control" data-lead placeholder="Lead name or leadgen_id"><button class="btn btn-default btn-sm" data-download>Download Lead by ID</button><button class="btn btn-default btn-sm" data-c360>Rebuild Customer360</button><button class="btn btn-default btn-sm" data-event>Rebuild Communication Event</button><button class="btn btn-default btn-sm" data-reassign>Reassign Counselor</button></div><div class="visa-panel"><textarea class="form-control" data-webhook rows="4" placeholder='{"leadgen_id":"..."}'></textarea><button class="btn btn-warning btn-sm" data-replay>Replay Webhook</button></div><pre class="visa-prod-json"></pre></div>`).appendTo(page.body);
    function show(r){root.find("pre").text(JSON.stringify(r.message||r,null,2))}
    root.on("click","[data-demo]",e=>frappe.call({method:"visa_crm.api.production_diagnostics.generate_demo",args:{kind:$(e.currentTarget).data("demo")},callback:show}));
    root.on("click","[data-retry]",()=>frappe.call({method:"visa_crm.api.production_diagnostics.retry_queue",args:{queue_name:root.find("[data-queue]").val()},callback:show}));
    root.on("click","[data-download]",()=>frappe.call({method:"visa_crm.api.production_diagnostics.download_lead_by_id",args:{leadgen_id:root.find("[data-lead]").val()},callback:show}));
    root.on("click","[data-c360]",()=>frappe.call({method:"visa_crm.api.production_diagnostics.rebuild_customer360",args:{lead:root.find("[data-lead]").val()},callback:show}));
    root.on("click","[data-event]",()=>frappe.call({method:"visa_crm.api.production_diagnostics.rebuild_communication_event",args:{lead:root.find("[data-lead]").val()},callback:show}));
    root.on("click","[data-reassign]",()=>frappe.call({method:"visa_crm.api.production_diagnostics.reassign_counselor",args:{lead:root.find("[data-lead]").val()},callback:show}));
    root.on("click","[data-replay]",()=>frappe.call({method:"visa_crm.api.production_diagnostics.replay_webhook",args:{payload:root.find("[data-webhook]").val()},callback:show}));
};
